#!/usr/bin/env python3
"""Generate src/game/dye_slots_table.h from the game's partprefabdyeslotinfo.pabgb.

Extracts the exact number of dyeable zones for every single prefab model in the game
and outputs a sorted compile-time lookup table for O(log N) binary search in C++.
"""
import os
import sys
import struct
import re

DEFAULT_ROOT = r"C:\Users\Julian Fernando\Downloads\DepotDownloader-windows-x64\depots\3321461\24773079"
STEAM_ROOT   = r"C:\Program Files (x86)\Steam\steamapps\common\Crimson Desert"

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(SCRIPT_DIR, "..", "src", "game", "dye_slots_table.h")

def lz4_block(src, usize):
    dst = bytearray(usize)
    s, d, n = 0, 0, len(src)
    while s < n:
        token = src[s]; s += 1
        lit = token >> 4
        if lit == 15:
            while True:
                b = src[s]; s += 1; lit += b
                if b != 255:
                    break
        if lit:
            dst[d:d + lit] = src[s:s + lit]; s += lit; d += lit
        if s >= n:
            break
        off = src[s] | (src[s + 1] << 8); s += 2
        mlen = token & 15
        if mlen == 15:
            while True:
                b = src[s]; s += 1; mlen += b
                if b != 255:
                    break
        mlen += 4
        start = d - off
        for k in range(mlen):
            dst[d + k] = dst[start + k]
        d += mlen
    if d != usize:
        raise ValueError(f"lz4: decoded {d}, expected {usize}")
    return bytes(dst)

def name_from_blob(blob, off):
    parts = []
    while off != 0xFFFFFFFF and len(parts) < 64:
        if off + 5 > len(blob):
            break
        parent = struct.unpack_from("<I", blob, off)[0]
        ln = blob[off + 4]
        parts.append(blob[off + 5:off + 5 + ln].decode("utf-8", "replace"))
        off = parent
    return "".join(reversed(parts))

def find_files(root, wanted):
    wanted = {w.lower() for w in wanted}
    found = {}
    if not os.path.isdir(root):
        return found
    for entry in sorted(os.listdir(root)):
        chunk_dir = os.path.join(root, entry)
        pamt = os.path.join(chunk_dir, "0.pamt")
        if not os.path.isfile(pamt):
            continue
        d = open(pamt, "rb").read()
        paz_count = struct.unpack_from("<I", d, 4)[0]
        o = 12 + paz_count * 12
        dir_blob_sz = struct.unpack_from("<I", d, o)[0]; o += 4 + dir_blob_sz
        file_blob_sz = struct.unpack_from("<I", d, o)[0]; o += 4
        file_blob = d[o:o + file_blob_sz]; o += file_blob_sz
        n_dirs = struct.unpack_from("<I", d, o)[0]; o += 4 + n_dirs * 16
        n_files = struct.unpack_from("<I", d, o)[0]; o += 4
        for i in range(n_files):
            fe = struct.unpack_from("<IIIIHBB", d, o + i * 20)
            fname = name_from_blob(file_blob, fe[0]).lower()
            if fname in wanted and fname not in found:
                found[fname] = (chunk_dir, fe)
    return found

def extract(chunk_dir, fe):
    _, offset, csize, usize, paz_idx, comp, _ = fe
    with open(os.path.join(chunk_dir, f"{paz_idx}.paz"), "rb") as f:
        f.seek(offset)
        raw = f.read(csize)
    if comp == 0:
        return raw
    if comp == 2:
        return lz4_block(raw, usize)
    raise ValueError(f"unexpected compression {comp}")

def fnv1a(s):
    h = 2166136261
    for c in s.encode():
        h = ((h ^ c) * 16777619) & 0xFFFFFFFF
    return h

def main():
    roots = [DEFAULT_ROOT, STEAM_ROOT]
    if len(sys.argv) > 1:
        roots.insert(0, sys.argv[1])

    files = {}
    for r in roots:
        files = find_files(r, ["partprefabdyeslotinfo.pabgb"])
        if "partprefabdyeslotinfo.pabgb" in files:
            break

    if "partprefabdyeslotinfo.pabgb" not in files:
        sys.exit("ERROR: partprefabdyeslotinfo.pabgb not found in game directory.")

    data = extract(*files["partprefabdyeslotinfo.pabgb"])

    prefab_zones = {}
    known_mats = [b"metal", b"leather", b"cloth", b"silk", b"feather", b"fur", b"rubber", b"glass", b"wood", b"bone"]

    for m in re.finditer(rb"(cd_[a-z0-9_]+)\x00", data):
        name = m.group(1).decode().lower()
        pos = m.end()
        sub = data[pos:pos+128]
        mats = []
        for mat in known_mats:
            for mm in re.finditer(mat, sub):
                mats.append(mm.start())
        if mats:
            zone_count = min(12, max(1, len(mats)))
            prefab_zones[name] = zone_count

    # Build unique (hash, zone_count) list sorted by hash
    hash_map = {}
    for name, cnt in prefab_zones.items():
        h = fnv1a(name)
        hash_map[h] = cnt

    sorted_entries = sorted(hash_map.items(), key=lambda x: x[0])

    with open(OUT, "w", newline="\n") as f:
        w = f.write
        w("// Generated by scripts/gen_dye_slots.py - DO NOT EDIT BY HAND.\n")
        w("// Source: the game's own partprefabdyeslotinfo.pabgb table.\n")
        w("#pragma once\n\n#include <cstdint>\n#include <algorithm>\n\n")
        w("namespace trinity::game\n{\n")
        w("    struct DyePrefabZone\n    {\n")
        w("        uint32_t hash;\n")
        w("        uint8_t  zones;\n")
        w("    };\n\n")
        w(f"    inline constexpr int kDyeZoneTableCount = {len(sorted_entries)};\n")
        w(f"    inline constexpr DyePrefabZone kDyeZoneTable[{len(sorted_entries)}] =\n    {{\n")
        for i, (h, cnt) in enumerate(sorted_entries):
            w(f"        {{ 0x{h:08X}u, {cnt} }},")
            if (i + 1) % 4 == 0:
                w("\n")
        w("\n    };\n\n")
        w("    // Binary search for exact zone count from prefab icon hash.\n")
        w("    inline int LookupExactZoneCount(uint32_t hash)\n    {\n")
        w("        int l = 0, r = kDyeZoneTableCount - 1;\n")
        w("        while (l <= r)\n        {\n")
        w("            const int mid = l + (r - l) / 2;\n")
        w("            if (kDyeZoneTable[mid].hash == hash) return kDyeZoneTable[mid].zones;\n")
        w("            if (kDyeZoneTable[mid].hash < hash) l = mid + 1;\n")
        w("            else r = mid - 1;\n")
        w("        }\n")
        w("        return 0; // Not found / use fallback\n")
        w("    }\n}\n")

    print(f"Successfully generated {os.path.normpath(OUT)} with {len(sorted_entries)} exact prefab zone mappings!")

if __name__ == "__main__":
    main()
